stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/

build:
  image: registry.gitlab.com/ix.ai/docker-buildx-qemu:latest
  stage: build
  services:
    - docker:dind
  retry: 2
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_CERT_PATH: "/certs/client"
    DOCKER_TLS: 'true'
    DOCKER_HOST: tcp://docker:2376/
    BUILDKIT_INLINE_CACHE: '1'
    DOCKER_DRIVER: overlay2
    BUILDX_PLATFORM: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/ppc64le
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel
    # Use docker-container driver to allow useful features (push/multi-platform)
    - docker context create MyContext
    - docker buildx create --driver docker-container --name MyContext --use MyContext
    - docker buildx inspect --bootstrap
  script:
    - docker buildx ls
    - update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel
    - chmod +x ./build/build.sh
    - . ./build/build.sh
  after_script:
    - docker build rm
  only:
    changes:
      - Dockerfile
      - rootfs/**/*
      - .gitlab-ci.yml
      - build/**/*

# the 'pages' job will deploy and build your site to the 'public' path
dockerhub-readme:
  stage: deploy
  variables:
    README_PATH: ./README.md
  image:
    name: sheogorath/readme-to-dockerhub:latest
    entrypoint: [""]
  script:
    - node /app/index.js
  only:
    refs:
      - master
    changes:
      - README.md
      - .gitlab-ci.yml

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  # requiring the environment of NodeJS 10
  image: node:10
  # add 'node_modules' to cache for speeding up builds
  cache:
    paths:
      - node_modules/ # Node modules and dependencies
  before_script:
    - npm install gitbook-cli -g # install gitbook
    - gitbook fetch 3.2.3 # fetch final stable version
    - gitbook install # add any requested plugins in book.json
  script:
    - gitbook build . public # build to public path
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    refs:
      - master
    changes:
      - README.md
      - .gitlab-ci.yml
